title: WishCowork
description: Premium Coworking Space in Jaipur
url: https://singhnatwar25.github.io/Wish1
baseurl: ""

# Build settings
markdown: kramdown
theme: null
permalink: /blog/:slug/

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude build-only files
exclude:
  - README.md
  - scripts/
  - node_modules/
  - vendor/

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: WishCowork Editorial
      category: Blog
      image: /resource/blog-images/Blog-GoWork-KITAS.jpg
      excerpt_separator: "<!--more-->"
